version: '3.7'

services:
  service-maxsol:
    build: .
    environment:
      - PORT_GOLANG=8083
      - MYSQL_USER=root
      - MYSQL_HOST=service-mariadb-maxsol
      - MYSQL_PORT=3306
      - MYSQL_PASSWORD=
      - MYSQL_DBNAME=maxsol
      - MYSQL_ROOT_PASSWORD=
    ports:
      - 8083:8083
    networks:
      - my-network
    command: 
      - make run-migration
    depends_on:
      - service-mariadb-maxsol

  service-mariadb-maxsol:
    image: mariadb:latest
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
    ports:
      - 3306
    volumes:
      - ~/golang/learndocker/mysql-two:/var/lib/mysql
      - ./mariadb/schema.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    networks:
      - my-network


networks:
  my-network:
    
